name: Test flow

on: [push]

jobs:
  install:
    name: Bootstrap core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: install
        run: |
          yarn install

  build:
    name: Build examples matrix
    runs-on: ubuntu-latest
    needs: [install]
    strategy:
      matrix:
        package: [packages/a, packages/b]
    steps:
      - name: build
        run: |
          echo ${{ matrix.package }}
      - name: upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package }}
          path: ${{ matrix.package }}/**

  examples:
    name: Build examples matrix
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        example: [official-storybook, cra-kitchen-sink]
    steps:
      - name: test
        run: |
          echo ${{ matrix.example }}
