name: Test flow

on: [push]

jobs:
  # install all node_modules
  install:
    name: Bootstrap core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: install
        run: yarn install
      - name: upload root
        uses: actions/upload-artifact@v2
        with:
          name: installed
          path: ${{ github.workspace }}/**

  # trying to build every package in parallel
  build:
    name: Build examples matrix
    runs-on: ubuntu-latest
    needs: [install]
    strategy:
      matrix:
        # the '/' char isn't allowed :(
        package: [
          [packages, a],
          [packages, b]
        ]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: installed
          path: ${{ github.workspace }}
      - name: build
        run: echo PACKAGE_ID # replace . with /
        env:
          PACKAGE_ID: ${{ join(matrix.package, '/') }}
      - name: upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ join(matrix.package, '.') }}
          path: ${{ github.workspace }}/${{ join(matrix.package, '/') }}/**

  # run every example in parallel
  examples:
    name: Build examples matrix
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        example: [official-storybook, cra-kitchen-sink]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: test
        run: |
          echo ${{ matrix.example }}
      - name: chromatic
        run: |
          echo ${{ matrix.example }}
