name: Test flow

on: [push]

jobs:
  build:
    name: Bootstrap core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-v2-${{ hashFiles('README.md') }}
          restore-keys: |
            build-v2-${{ env.cache-name }}-
            build-v2-
      - name: install, bootstrap
        run: |
          echo "bootstrap"

  examples:
    name: Build examples matrix
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2]
    steps:
      - name: test
        run: |
          echo ${{ matrix.mongodb-version }}
